theme: jekyll-theme-minimal
title: Aaron Technical Notes
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts